// GENERATED by build.py from data/portfolio_data.yaml and data/versions.yaml. Do not edit.
export const APPS = [
 {
  "id": "nb_vendor_portal_pro",
  "title": "Vendor Portal Pro",
  "line": "Portals",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$99",
    "module_version": "1.8.5",
    "store": "https://apps.odoo.com/apps/modules/19.0/nb_vendor_portal_pro/"
   },
   {
    "odoo": "18",
    "price": "$99",
    "module_version": "1.8.5",
    "store": "https://apps.odoo.com/apps/modules/18.0/nb_vendor_portal_pro/"
   }
  ],
  "summary": "Vendor portal: onboarding, RFQ quoting, PO acknowledgment, vendor bills and payments",
  "about": "A full supplier self-service portal for Odoo Purchase. Vendors onboard themselves, quote on RFQs, acknowledge purchase orders, send advance shipping notices, upload compliance documents and track bills and payments, while buyers keep scorecards, disputes and price comparisons inside Odoo.",
  "features": [
   "Vendor onboarding with compliance documents and versioning",
   "RFQ quoting, price requests and side-by-side price comparison",
   "PO acknowledgment, advance shipping notices (ASN) and dispute handling",
   "Vendor scorecards, alerts and read receipts",
   "Vendor bills and payment visibility in the portal"
  ],
  "works_with": [
   "Purchase",
   "Purchase Requisition",
   "Accounting",
   "Portal",
   "Contacts"
  ],
  "page": "https://neuralbytea.github.io/apps/nb_vendor_portal_pro/"
 },
 {
  "id": "salesperson_portal",
  "title": "Field Sales Booking",
  "line": "Portals",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$99",
    "module_version": "2.5.0",
    "store": "https://apps.odoo.com/apps/modules/19.0/salesperson_portal/"
   },
   {
    "odoo": "18",
    "price": "$99",
    "module_version": "2.5.0",
    "store": "https://apps.odoo.com/apps/modules/18.0/salesperson_portal/"
   }
  ],
  "summary": "Field sales rep portal: reps book orders for customers from the portal, no user seat",
  "about": "Lets field sales reps book orders for their customers from the Odoo portal without consuming an internal user seat. Includes catalog and cart, credit checks, discounts and rewards, customer creation, invoices, support tickets and a commission engine with plans and rules.",
  "features": [
   "Reps work as portal users, so no internal user seat is needed",
   "Catalog, cart, credit check and discount / reward handling",
   "Commission plans and rules with commission lines",
   "Customers, invoices, offers and support tickets from one dashboard",
   "Automated test suite covering the ordering flow"
  ],
  "works_with": [
   "Sales",
   "Accounting",
   "Portal",
   "Mail"
  ],
  "page": "https://neuralbytea.github.io/apps/salesperson_portal/"
 },
 {
  "id": "nb_services_billing_pro",
  "title": "Services Billing Pro",
  "line": "Portals",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$99",
    "module_version": "1.0.7",
    "store": "https://apps.odoo.com/apps/modules/19.0/nb_services_billing_pro/"
   },
   {
    "odoo": "18",
    "price": "$99",
    "module_version": "1.0.7",
    "store": "https://apps.odoo.com/apps/modules/18.0/nb_services_billing_pro/"
   }
  ],
  "summary": "Employee rate cards, automatic margin per timesheet line, portal timer and order-based billing",
  "about": "Adds multi-tier rate cards (billing rate and cost rate per employee, customer, project and service type) to Odoo timesheets. Every timesheet line gets its margin automatically, employees log time from a portal timer, and non-billable work can be hidden or shown on the invoice at zero price.",
  "features": [
   "Rate cards by employee, customer, project, service type and date range",
   "Automatic billing amount, cost amount and margin on each timesheet line",
   "Portal timer and manual time entry",
   "Margin report and team overview for managers",
   "Non-billable time shown at 0.00 on the invoice, or hidden",
   "Cost rates never exposed to customers"
  ],
  "works_with": [
   "Sales Timesheet",
   "Projects",
   "Invoicing",
   "Portal"
  ],
  "page": "https://neuralbytea.github.io/apps/nb_services_billing_pro/"
 },
 {
  "id": "nb_customer_portal_pro",
  "title": "Customer Portal Pro",
  "line": "Portals",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$99",
    "module_version": "1.3.5",
    "store": "https://apps.odoo.com/apps/modules/19.0/nb_customer_portal_pro/"
   },
   {
    "odoo": "18",
    "price": "$99",
    "module_version": "1.3.5",
    "store": "https://apps.odoo.com/apps/modules/18.0/nb_customer_portal_pro/"
   }
  ],
  "summary": "Customer portal: self-service ordering, order-to-cash dashboard, invoices, payments, tickets",
  "about": "Turns the Odoo customer portal into a self-service workspace: customers place orders, follow the order-to-cash flow on a dashboard, view invoices and payments, receive alerts and raise support tickets.",
  "features": [
   "Self-service ordering from the portal",
   "Order-to-cash dashboard",
   "Invoices and payments in one place",
   "Support tickets and portal alerts with read tracking",
   "Scheduled mail notifications"
  ],
  "works_with": [
   "Sales",
   "Accounting",
   "Contacts",
   "Portal"
  ],
  "page": "https://neuralbytea.github.io/apps/nb_customer_portal_pro/"
 },
 {
  "id": "nb_employee_self_service",
  "title": "Employee Self Service",
  "line": "Portals",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$119",
    "module_version": "2.0.4",
    "store": "https://apps.odoo.com/apps/modules/19.0/nb_employee_self_service/"
   },
   {
    "odoo": "18",
    "price": "$119",
    "module_version": "2.0.4",
    "store": "https://apps.odoo.com/apps/modules/18.0/nb_employee_self_service/"
   }
  ],
  "summary": "Internal self-service portal: profile, time off, attendance, expenses and payslips",
  "about": "A single self-service workspace on the standard Odoo /my pages where your internal users handle their own HR admin instead of emailing HR. It installs on any Odoo database and lights up payslips and timesheets automatically when those apps are present.",
  "features": [
   "My Profile: editable private info, avatar, ID-card scans, resume and skills",
   "My Time Off: balances, request form, and a filterable manager approval inbox",
   "My Attendances: check in and out, a full-month timeline and manager-approved corrections",
   "My Overtime: extra hours by month, comp-off balance and requests",
   "My Expenses: reports, quick log form and totals",
   "Payslips with in-page PDF preview (Enterprise) and timesheets, when those apps are installed",
   "One-click user creation from the employee form"
  ],
  "works_with": [
   "Employees",
   "Time Off",
   "Portal",
   "Mail"
  ],
  "page": "https://neuralbytea.github.io/apps/nb_employee_self_service/"
 },
 {
  "id": "portal_ext",
  "title": "Portal Sidebar Pro",
  "line": "Portals",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$49",
    "module_version": "1.0.7",
    "store": "https://apps.odoo.com/apps/modules/19.0/portal_ext/"
   },
   {
    "odoo": "18",
    "price": "$49",
    "module_version": "1.0.7",
    "store": "https://apps.odoo.com/apps/modules/18.0/portal_ext/"
   }
  ],
  "summary": "Collapsible sidebar, live dashboard and redesigned My Account for the Odoo customer portal",
  "about": "A collapsible, auto-built sidebar for the Odoo portal /my area, a redesigned home dashboard and cleaner My Details and Security pages. Pairs with the NeuralBytea portals.",
  "features": [
   "Collapsible sidebar built from the portal entries",
   "Live portal home dashboard",
   "Redesigned My Details and Security pages"
  ],
  "works_with": [
   "Portal"
  ],
  "page": "https://neuralbytea.github.io/apps/portal_ext/"
 },
 {
  "id": "payment_Mastercard",
  "title": "Mastercard MPGS Payment",
  "line": "Payments",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$49",
    "module_version": "1.0.5",
    "store": "https://apps.odoo.com/apps/modules/19.0/payment_Mastercard/"
   },
   {
    "odoo": "18",
    "price": "$49",
    "module_version": "1.0.4",
    "store": "https://apps.odoo.com/apps/modules/18.0/payment_Mastercard/"
   }
  ],
  "summary": "Mastercard (MPGS) Hosted Checkout payment provider for secure online payments",
  "about": "Payment provider for the Mastercard Payment Gateway Services (MPGS) Hosted Checkout with 3-D Secure. Payments are posted automatically and reconciled with invoices.",
  "features": [
   "Hosted Checkout, so card data never touches your server",
   "3-D Secure support",
   "Automatic payment posting and invoice reconciliation",
   "Standard Odoo payment provider configuration"
  ],
  "works_with": [
   "Payment Providers",
   "Invoicing"
  ],
  "page": "https://neuralbytea.github.io/apps/payment_Mastercard/"
 },
 {
  "id": "employee_loan_management_enterprise",
  "title": "Employee Loan Pro",
  "line": "HR & Payroll",
  "edition": "Enterprise (needs Payroll)",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$49",
    "module_version": "1.0.10",
    "store": "https://apps.odoo.com/apps/modules/19.0/employee_loan_management_enterprise/"
   },
   {
    "odoo": "18",
    "price": "$49",
    "module_version": "1.0.8",
    "store": "https://apps.odoo.com/apps/modules/18.0/employee_loan_management_enterprise/"
   },
   {
    "odoo": "17",
    "price": "$49",
    "module_version": "1.0.0",
    "store": "https://apps.odoo.com/apps/modules/17.0/employee_loan_management_enterprise/"
   }
  ],
  "summary": "Employee loans and salary advances with automatic payroll deduction and analytics",
  "about": "Manages employee loans and salary advances end to end: loan types, installment schedules, rescheduling, accounting configuration and automatic deduction on the payslip, with an analytics dashboard.",
  "features": [
   "Loan types and installment schedules",
   "Automatic payroll deduction through payslip inputs",
   "Loan rescheduling wizard",
   "Accounting integration and configuration",
   "Analytics dashboard and portal access"
  ],
  "works_with": [
   "Payroll",
   "Accounting",
   "Employees"
  ],
  "page": "https://neuralbytea.github.io/apps/employee_loan_management_enterprise/"
 },
 {
  "id": "hr_attendance_board",
  "title": "Attendance Leave Gantt",
  "line": "HR & Payroll",
  "edition": "Enterprise (needs Contracts)",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$24.99",
    "module_version": "2.0.6",
    "store": "https://apps.odoo.com/apps/modules/19.0/hr_attendance_board/"
   },
   {
    "odoo": "18",
    "price": "$24.99",
    "module_version": "2.0.5",
    "store": "https://apps.odoo.com/apps/modules/18.0/hr_attendance_board/"
   },
   {
    "odoo": "17",
    "price": "$24.99",
    "module_version": "2.0.0",
    "store": "https://apps.odoo.com/apps/modules/17.0/hr_attendance_board/"
   }
  ],
  "summary": "Color-coded attendance and leave Gantt: office, remote and hybrid, click-to-edit, KPIs",
  "about": "A colour-coded Gantt board of attendance and leave that separates office, remote and hybrid days, with click-to-edit, remote-work periods on contracts and on-site versus remote KPIs.",
  "features": [
   "Gantt of attendance and leave in one view",
   "Office, remote and hybrid classification",
   "Click-to-edit from the board",
   "Remote work periods on contracts",
   "On-site vs remote KPI dashboard"
  ],
  "works_with": [
   "Attendances",
   "Time Off",
   "Employees",
   "Contracts"
  ],
  "page": "https://neuralbytea.github.io/apps/hr_attendance_board/"
 },
 {
  "id": "nb_payroll_dashboard",
  "title": "Payroll Dashboard Pro",
  "line": "Dashboards",
  "edition": "Enterprise (needs Payroll)",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$29",
    "module_version": "1.0.8",
    "store": "https://apps.odoo.com/apps/modules/19.0/nb_payroll_dashboard/"
   },
   {
    "odoo": "18",
    "price": "$29",
    "module_version": "1.0.7",
    "store": "https://apps.odoo.com/apps/modules/18.0/nb_payroll_dashboard/"
   }
  ],
  "summary": "Owl payroll dashboard and Excel/PDF salary report, zero configuration",
  "about": "A zero-configuration payroll dashboard built with Owl, plus a wizard that exports salary reports to Excel and PDF.",
  "features": [
   "Owl dashboard over payslip data",
   "Excel and PDF salary report",
   "No setup needed after install"
  ],
  "works_with": [
   "Payroll",
   "Accounting"
  ],
  "page": "https://neuralbytea.github.io/apps/nb_payroll_dashboard/"
 },
 {
  "id": "sale_payment_dashboard",
  "title": "Sales & Payment Dashboard",
  "line": "Dashboards",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$49",
    "module_version": "1.2.4",
    "store": "https://apps.odoo.com/apps/modules/19.0/sale_payment_dashboard/"
   },
   {
    "odoo": "18",
    "price": "$49",
    "module_version": "1.2.3",
    "store": "https://apps.odoo.com/apps/modules/18.0/sale_payment_dashboard/"
   },
   {
    "odoo": "17",
    "price": "$49",
    "module_version": "1.0.0",
    "store": "https://apps.odoo.com/apps/modules/17.0/sale_payment_dashboard/"
   }
  ],
  "summary": "Owl dashboards for Sales, Invoices and Payments: live KPIs, recovery, customer trends",
  "about": "Owl dashboards that link sale orders, invoices and payments: live KPIs, recovery tracking, customer revenue ranking, product category mix and 12-month trends.",
  "features": [
   "Live sales, invoice and payment KPIs",
   "Recovery tracking for outstanding amounts",
   "Customer revenue ranking and category mix",
   "12-month trends"
  ],
  "works_with": [
   "Sales",
   "Accounting"
  ],
  "page": "https://neuralbytea.github.io/apps/sale_payment_dashboard/"
 },
 {
  "id": "nb_smart_list_search_pro",
  "title": "Smart List Search Pro",
  "line": "Backend UI",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$59",
    "module_version": "1.0.3",
    "store": "https://apps.odoo.com/apps/modules/19.0/nb_smart_list_search_pro/"
   },
   {
    "odoo": "18",
    "price": "$59",
    "module_version": "1.0.1",
    "store": "https://apps.odoo.com/apps/modules/18.0/nb_smart_list_search_pro/"
   }
  ],
  "summary": "Sticky column filters, AI search ranks and groups your Odoo list data instantly",
  "about": "Adds sticky column filters to Odoo list views and an AI search that ranks and groups records. Supports multiple AI model providers with per-company credentials and saved search profiles.",
  "features": [
   "Sticky per-column filters on list views",
   "AI-assisted search that ranks and groups results",
   "Choice of AI providers and models",
   "Saved search profiles"
  ],
  "works_with": [
   "Web",
   "Mail"
  ],
  "page": "https://neuralbytea.github.io/apps/nb_smart_list_search_pro/"
 },
 {
  "id": "mail_ext",
  "title": "Chatter Workspace Pro",
  "line": "Backend UI",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$29",
    "module_version": "2.1.2",
    "store": "https://apps.odoo.com/apps/modules/19.0/mail_ext/"
   },
   {
    "odoo": "18",
    "price": "$29",
    "module_version": "2.1.1",
    "store": "https://apps.odoo.com/apps/modules/18.0/mail_ext/"
   }
  ],
  "summary": "Hide, resize chatter with per-user memory; admin layout rules; preview toggle",
  "about": "Lets users hide and resize the chatter with their choice remembered per user, while admins set layout rules per model and company.",
  "features": [
   "Hide and resize chatter",
   "Per-user memory of layout",
   "Admin layout rules",
   "Preview toggle",
   "Translated (3 languages)"
  ],
  "works_with": [
   "Discuss"
  ],
  "page": "https://neuralbytea.github.io/apps/mail_ext/"
 },
 {
  "id": "pane_split_view",
  "title": "Split View Pro",
  "line": "Backend UI",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$24.99",
    "module_version": "1.0.5",
    "store": "https://apps.odoo.com/apps/modules/19.0/pane_split_view/"
   },
   {
    "odoo": "18",
    "price": "$24.99",
    "module_version": "1.0.4",
    "store": "https://apps.odoo.com/apps/modules/18.0/pane_split_view/"
   }
  ],
  "summary": "Master-detail split pane for every Odoo list view, preview and edit side by side",
  "about": "A master-detail split pane for Odoo list views so you can preview and edit records beside the list.",
  "features": [
   "Split pane on list views",
   "Preview and edit side by side"
  ],
  "works_with": [
   "Web"
  ],
  "page": "https://neuralbytea.github.io/apps/pane_split_view/"
 },
 {
  "id": "web_home_menu",
  "title": "Home Menu Enterprise UI",
  "line": "Backend UI",
  "edition": "Community",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$20",
    "module_version": "1.0.5",
    "store": "https://apps.odoo.com/apps/modules/19.0/web_home_menu/"
   },
   {
    "odoo": "18",
    "price": "$20",
    "module_version": "1.0.4",
    "store": "https://apps.odoo.com/apps/modules/18.0/web_home_menu/"
   }
  ],
  "summary": "Enterprise-like Home Menu for Community Edition",
  "about": "Brings an Enterprise-style home menu to Odoo Community.",
  "features": [
   "Enterprise-like app grid home menu for Community"
  ],
  "works_with": [
   "Web"
  ],
  "page": "https://neuralbytea.github.io/apps/web_home_menu/"
 },
 {
  "id": "web_appbar",
  "title": "Sidebar App Navigation",
  "line": "Backend UI",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$15",
    "module_version": "1.0.7",
    "store": "https://apps.odoo.com/apps/modules/19.0/web_appbar/"
   },
   {
    "odoo": "18",
    "price": "$10",
    "module_version": "1.0.6",
    "store": "https://apps.odoo.com/apps/modules/18.0/web_appbar/"
   }
  ],
  "summary": "Collapsible sidebar and appbar navigation with modern design for Odoo",
  "about": "A collapsible sidebar and appbar navigation with a modern design. Works with Web UI Extensions.",
  "features": [
   "Collapsible sidebar navigation",
   "Modern appbar design"
  ],
  "works_with": [
   "Web",
   "Web UI Extensions"
  ],
  "page": "https://neuralbytea.github.io/apps/web_appbar/"
 },
 {
  "id": "web_ext",
  "title": "Web UI Extensions",
  "line": "Backend UI",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$5",
    "module_version": "1.0.6",
    "store": "https://apps.odoo.com/apps/modules/19.0/web_ext/"
   },
   {
    "odoo": "18",
    "price": "$5",
    "module_version": "1.0.5",
    "store": "https://apps.odoo.com/apps/modules/18.0/web_ext/"
   }
  ],
  "summary": "Modern UI enhancements and customizations for Odoo web interface",
  "about": "Shared UI enhancements for the Odoo web client. Required by Sidebar App Navigation.",
  "features": [
   "Modern UI enhancements for the web client"
  ],
  "works_with": [
   "Web"
  ],
  "page": "https://neuralbytea.github.io/apps/web_ext/"
 },
 {
  "id": "nb_ai_chatbot",
  "title": "AI Chat Assistant",
  "line": "AI Assistant",
  "edition": "Community & Enterprise",
  "licence": "OPL-1",
  "versions": [
   {
    "odoo": "19",
    "price": "$19",
    "module_version": "1.0.1",
    "store": "https://apps.odoo.com/apps/modules/19.0/nb_ai_chatbot/"
   }
  ],
  "summary": "AI chatbot for Odoo: ChatGPT, Claude and Gemini query your data and create records on confirm",
  "about": "A floating AI chat bubble on every screen of Odoo Community and Enterprise. Connect your own AI model with your own API key, then chat with your Odoo data. The assistant always runs with the access rights of the signed-in user.",
  "features": [
   "Bring your own AI agent in 10 seconds: pick a provider, paste the API key",
   "OpenAI (ChatGPT), Claude, Gemini, Groq, NVIDIA NIM, OpenCode Zen, Ollama or any OpenAI-compatible API",
   "Ask questions about your data: it searches, counts and totals records",
   "Every answer lists the records it used, with a link to open them",
   "Create or update records by asking, confirming each change with one click"
  ],
  "works_with": [
   "Discuss",
   "Web"
  ],
  "page": "https://neuralbytea.github.io/apps/nb_ai_chatbot/"
 },
 {
  "id": "payment_provider_ngenius",
  "title": "N-Genius Payment Provider",
  "line": "Payments",
  "edition": "Community & Enterprise",
  "licence": "LGPL-3",
  "versions": [
   {
    "odoo": "19",
    "price": "Free",
    "module_version": "1.1.1",
    "store": "https://apps.odoo.com/apps/modules/19.0/payment_provider_ngenius/"
   }
  ],
  "summary": "N-Genius card payments in Odoo: hosted checkout, webhooks, sandbox and full refunds",
  "about": "Accept online payments in Odoo with N-Genius Online by Network International. Customers pay on a secure hosted checkout, payment status updates automatically, and you can refund in full from Odoo. Requires an active N-Genius merchant account.",
  "features": [
   "Secure hosted checkout",
   "Sandbox and production environments",
   "Automatic payment status updates through webhooks",
   "Full refund support from Odoo"
  ],
  "works_with": [
   "Payment Providers",
   "Invoicing"
  ],
  "page": "https://neuralbytea.github.io/apps/payment_provider_ngenius/"
 }
];
export const COMPANY = {
 "name": "NeuralBytea",
 "site": "https://neuralbytea.github.io",
 "email": "neuralbytea@gmail.com",
 "location": "Lahore, Pakistan",
 "store": "https://apps.odoo.com/apps/browse?repo_maintainer_id=1172096",
 "contact_page": "https://neuralbytea.github.io/contact/",
 "facts": [
  "Apps are built for Odoo 17, 18 and 19; Odoo 19 has the full range, Odoo 17 has only Employee Loan Pro, Attendance Leave Gantt and Sales & Payment Dashboard.",
  "Most apps run on Community and Enterprise; Employee Loan Pro, Attendance Leave Gantt and Payroll Dashboard Pro need Enterprise features (Payroll or Contracts).",
  "Install from the Odoo Apps Store like any app. Paid apps: one-time price per app, OPL-1 licence, no subscription. N-Genius payment provider is free (LGPL-3).",
  "Custom development: custom Odoo modules, portals, payment and API integrations, dashboards and migrations, fixed price or hourly.",
  "Support: contact form or the app's store page; replies by email.",
  "Employee Self Service needs internal users. The AI Chat Assistant uses the customer's own AI provider and API key and respects each user's access rights."
 ]
};
